# app/shutdown.py
from __future__ import annotations

import atexit
import signal
import sys
import threading
from typing import Callable, Optional

# On Windows we can also trap console close events (clicking the X)
_IS_WIN = sys.platform.startswith("win")
_once_flag = threading.Event()


def _call_once(func: Callable[[], None]) -> None:
    if not _once_flag.is_set():
        _once_flag.set()
        try:
            func()
        except Exception:
            # Never let shutdown hooks raise
            pass


def install(on_exit: Callable[[], None]) -> None:
    """
    Register best-effort process-exit handlers:
      - atexit
      - SIGINT / SIGTERM (and SIGBREAK on Windows)
      - Windows console control events (CTRL_C_EVENT, CTRL_CLOSE_EVENT, etc.)

    on_exit() will be called once, as early as possible during shutdown.
    """
    # 1) atexit always fires on normal termination
    atexit.register(lambda: _call_once(on_exit))

    # 2) POSIX/Windows signals
    def _sig_handler(signum, frame):
        _call_once(on_exit)
        # re-raise default behavior for immediate termination (esp. SIGTERM)
        # For SIGINT, letting default after notifying is fine.
        # We don't explicitly re-raise; process will continue to exit.
    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            signal.signal(sig, _sig_handler)
        except Exception:
            pass
    if _IS_WIN:
        # SIGBREAK is generated by Ctrl+Break on Windows
        try:
            signal.signal(signal.SIGBREAK, _sig_handler)  # type: ignore[attr-defined]
        except Exception:
            pass

    # 3) Windows console close events via SetConsoleCtrlHandler
    if _IS_WIN:
        try:
            import ctypes
            from ctypes import wintypes

            PHANDLER_ROUTINE = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.DWORD)

            # Handler types
            CTRL_C_EVENT = 0
            CTRL_BREAK_EVENT = 1
            CTRL_CLOSE_EVENT = 2
            CTRL_LOGOFF_EVENT = 5
            CTRL_SHUTDOWN_EVENT = 6

            def _handler(ctrl_type: int) -> bool:
                # Notify once, return True to indicate we've handled it
                _call_once(on_exit)
                # Return True so Windows gives us a moment to finish
                return True

            _handler_c = PHANDLER_ROUTINE(_handler)
            kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
            ok = kernel32.SetConsoleCtrlHandler(_handler_c, True)
            if not ok:
                # If this fails, we still have atexit + signals
                pass

            # Keep a reference so it isn't GC'd
            install._handler_ref = _handler_c  # type: ignore[attr-defined]

        except Exception:
            # If ctypes path fails, signals+atexit still cover most cases
            pass
